import './style/globals.scss';

import type { Metadata } from 'next';

import { suisseIntl } from './fonts';

export const metadata: Metadata = {
  title: 'Двери «Legion»',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/images/icons/favicon/favicon.ico' },
      { url: '/images/icons/favicon/favicon-32x32.png', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`background-noise ${suisseIntl.variable} `}>{children}</body>
    </html>
  );
}
